# -*- coding: utf-8 -*-
"""Senior_Design_YahyaCombined_3_20_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apCbrpUsqhKgF_MUpx44A_nDjjbWlVFG
"""

pip install -U sentence-transformers cleanlab hdbscan umap umap-learn[plot] wordcloud gensim==3.8.3 --upgrade nltk

# mount google drive, sets folder for saving plots and figures, creates the folders if they do not exist
import os
from google.colab import drive

drive.mount('/content/drive')
folder_path = '/content/drive/MyDrive/Saved_Figures_SD/WordClouds/'

if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"Created directory {folder_path}")
else:
    print(f"Directory {folder_path} already exists")

# Creates Timestamp variable for saving off results
import datetime

now = datetime.datetime.now()
timestamp = now.strftime("%Y-%m-%d")
print(timestamp)

# IMPORTS
from cleanlab.outlier import OutOfDistribution
from enum import Enum
import os
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from PIL import Image
 #from seg_algorithm import get_optimal_splits, get_segmented_sentences
from sentence_transformers import SentenceTransformer
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.datasets import fetch_openml
from sklearn.decomposition import PCA
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, TfidfTransformer, ENGLISH_STOP_WORDS
from sklearn.metrics import adjusted_mutual_info_score, adjusted_rand_score
from sklearn.preprocessing import StandardScaler
from transformers import AutoTokenizer, AutoModel
from umap.umap_ import INT32_MAX
from wordcloud import WordCloud
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim import corpora
import gensim
from pprint import pprint
#from seg_algorithm import get_optimal_splits, get_segmented_sentences
import cleanlab
import hdbscan
import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
import re
import sklearn.cluster as cluster
import string
import torch
import torch.nn.functional as F
import umap
import unicodedata
from gensim.models import KeyedVectors
from statistics import mean
from nltk.stem import WordNetLemmatizer
from wordcloud import STOPWORDS
import csv
nltk.download('averaged_perceptron_tagger') 
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Constants
URL = "https://raw.githubusercontent.com/yahya010/DocClustering/main/Pres_Speeches/presidential_speeches.csv"
stop_words = set(stopwords.words('english')) # switched to sklearn as it is larger than nltk stopwords
dataset = pd.read_csv(URL)
p = 0.65 #increase p = no of segments decreases

# Initialization
SEPERATE_BY_PRES = False

# Pre-Processing
MIN_SENTENCE_WORDS = 5
PLOT_SPEECHLEN_HIST = True
MIN_SPEECH_SENTENCE_COUNT = 10 # 10 sentences needed for cleanlab embedding

# Cleanlab
OUTLIER_SCORE_CUTOFF = 0.6
PRINT_CLEANLAB_ANALYSIS = True

# Lemmatize
num_lemmatized_words = 10

# Number of clusters - filtered
num_filtered_clusters = 32
num_unfiltered_clusters = 25

# Traffic control
coherenceRan_Filtered = False
initialWordcloudRan_Filtered = False
coherenceRan_Unfiltered = False
initialWordcloudRan_Unfiltered = False

# kmeans
kmeans_seed = 4  #By default kmeans seed is random, by setting the seed, the results are repeatable. 2^32 or 2^64 possible random states.

## REF: https://colab.research.google.com/github/gal-a/blog/blob/master/docs/notebooks/nlp/nlp_tf-idf_clustering.ipynb#scrollTo=EbAMAIFFV_xh

# List of Presidents
class PresidentIndex(Enum):
  George_Washington = 0
  John_Adams = 1
  Thomas_Jefferson = 2
  James_Madison = 3
  James_Monroe = 4
  John_Quincy_Adams = 5
  Andrew_Jackson = 6
  Martin_Van_Buren = 7
  William_Harrison = 8
  John_Tyler = 9
  James_Polk = 10
  Zachary_Taylor = 11
  Millard_Fillmore = 12
  Franklin_Pierce = 13
  James_Buchanan = 14
  Abraham_Lincoln = 15
  Andrew_Johnson = 16
  Ulysses_Grant = 17
  Rutherford_Hayes = 18
  James_Garfield = 19
  Chester_Arthur = 20
  Grover_Cleveland_1 = 21
  Benjamin_Harrison = 22
  Grover_Cleveland_2 = 23
  William_McKinley = 24
  Theodore_Roosevelt = 25
  William_Taft = 26
  Woodrow_Wilson = 27
  Warren_Harding = 28
  Calvin_Coolidge = 29
  Herbert_Hoover = 30
  Franklin_Roosevelt = 31
  Harry_Truman = 32
  Dwight_Eisenhower = 33 
  John_Kennedy= 34
  Lyndon_Johnson = 35
  Richard_Nixon = 36
  Gerald_Ford = 37
  James_Carter = 38
  Ronald_Reagan = 39
  George_H_W_Bush = 40
  Bill_Clinton = 41
  George_W_Bush = 42
  Barack_Obama = 43
  Donald_Trump = 44

# Set Presidents to use
PRESIDENTS = [PresidentIndex.Ronald_Reagan, PresidentIndex.George_H_W_Bush, PresidentIndex.Bill_Clinton, PresidentIndex.George_W_Bush, PresidentIndex.Barack_Obama, PresidentIndex.Donald_Trump];
PRESIDENT_NAMES = [n.name for n in PRESIDENTS]

# Get stopwords, stemmer and lemmatizer
stemmer = nltk.stem.PorterStemmer()
lemmatizer = nltk.stem.WordNetLemmatizer()
general_stopwords = ENGLISH_STOP_WORDS  # note: sklearn has a longer list than nltk.corpus.stopwords.words('english')
additional_stopwords = []


# Get data samples and associated president
speeches = []
speech_classes = []

## TODO: VERIFY ALL PRES NAMES MATCH
# Tested: Washington, Lincoln

for index, row in dataset.iterrows():
  underscoreName = row['President'].replace(' ', '_')
  underscoreName = underscoreName.translate(str.maketrans('','','.'))
  
  if underscoreName in PRESIDENT_NAMES:
    speeches.append(row['Transcript'])
    speech_classes.append(PresidentIndex[underscoreName].value)

def z_score(data):
    """Calculates the z-scores for a given dataset."""
    mean = np.mean(data)
    std_dev = np.std(data)
    z_scores = (data - mean) / std_dev
    return z_scores

def squared_sum(x):
  """ return 3 rounded square rooted value """
  return round(np.sqrt(sum([a*a for a in x])),3)

def cos_similarity(x,y):
  """ return cosine similarity between two lists """
  numerator = sum(a*b for a,b in zip(x,y))
  denominator = squared_sum(x)*squared_sum(y)
  return round(numerator/float(denominator),3)

def color_func(word=None, font_size=None,
                     position=None, orientation=None,
                     font_path=None, random_state=None):
    colors = [[4, 77, 82],
              [25, 74, 85],
              [82, 43, 84],
              [158, 48, 79]]
    rand = random_state.randint(0, len(colors) - 1)
    return "hsl({}, {}%, {}%)".format(colors[rand][0], colors[rand][1], colors[rand][2])

# ------------------------------------------------------------------------------------------------
# Rishabhs Functions
# Get the final coherence scores for each cluster
def calcFinalScores(coherenceScores, finalWeights):
  listScores = []
  for i in range(len(coherenceScores)):
    sum = 0
    for j in range(len(coherenceScores[i])):
      sum += finalWeights[i][j]*coherenceScores[i][j]
    listScores.append(sum) # Multiply sum by 1000 to make scores more readable (this can be changed). Divide by 45 to get average. 
  return listScores


# Use temporary weights to get final weights. The weights will be finalized by normalizing them.

def calcFinalWeights(pairWeights):
  finalWeights = []
  for i in range(len(pairWeights)):
    curWeights = pairWeights[i]
    sumWeights = 0
    for j in range(len(curWeights)):
      # sumWeights = sumWeights + math.exp(curWeights[j])
      sumWeights = sumWeights + curWeights[j]
    tempFinalWeights = []
    for j in range(len(curWeights)):
      # tempFinalWeights.append(math.exp(curWeights[j]) / sumWeights)
      tempFinalWeights.append(curWeights[j] / sumWeights) # Normalize the weights
    finalWeights.append(tempFinalWeights)
  # sum = 0
  # for i in range(len(finalWeights[0])):
  #   sum = sum + finalWeights[1][i]

  return finalWeights

def calcCoherence1(clusterStrings):
  corpus = clusterStrings # set corpus as the list of clusters with corresponding texts as strings
  corpus = [' '.join(cluster) for cluster in clusterStrings]
  # Use TF-IDF
  vectorizer = TfidfVectorizer(stop_words=list(STOPWORDS), norm=None, smooth_idf=False) 
  X = vectorizer.fit_transform(corpus)
  idf = vectorizer.idf_
  idf = idf - 1
  countVectorizer = CountVectorizer(stop_words=list(STOPWORDS))
  tf = countVectorizer.fit_transform(corpus)
  tf = tf.toarray()
  tfidf = tf*idf

  lemmatizer = WordNetLemmatizer()
  coherenceScores = []
  pairWeights = []

  for i in range(len(clusterStrings)): # loop through all clusters

    df = pd.DataFrame(tfidf[i], index=vectorizer.get_feature_names_out(), columns=["TF-IDF"])
    dfs = df.sort_values('TF-IDF', ascending=False) 

    curList = dfs.index.to_list()
    curListLem = []
    curList10 = []

    # Get top 10 words (lemmatized)
    w = 0
    c = 0
    while c < num_lemmatized_words:
      word = curList[w]
      curWord = lemmatizer.lemmatize(word)
      if curWord not in curListLem and curWord in model.vocab:
        curListLem.append(curWord)
        c = c + 1
      w = w + 1

    # Get pair-wise scores
    tempScore = []
    tempPairWeights = []
    for a in range(len(curListLem)):
      for b in range(a, len(curListLem)):
        if a != b:
          w1 = curListLem[a]
          w2 = curListLem[b]
          weight1 = list(model.vocab.keys()).index(w1) # Get Zipf rank of word 1
          weight2 = list(model.vocab.keys()).index(w2) # Get Zipf rank of word 2
          tempPairWeights.append(mean([weight1, weight2]))
          # tempPairWeigts.append(math.log(weight1, 10) + math.log(weight2, 10) / 2)
          tempScore.append(model.similarity(w1, w2))
    pairWeights.append(tempPairWeights)
    coherenceScores.append(tempScore)
  return [pairWeights, coherenceScores] # return list of weights and temporary scores
# wrapper function to calculate coherence scores

def calcCoherence(clusterStrings):
  pairWeights_and_coherenceScores1 = calcCoherence1(clusterStrings)
  pairWeights = pairWeights_and_coherenceScores1[0]
  coherenceScores1 = pairWeights_and_coherenceScores1[1]
  finalWeights = calcFinalWeights(pairWeights)
  finalScores = calcFinalScores(coherenceScores1, finalWeights)
  return finalScores
# ------------------------------------------------------------------------------------------------

# Pre-Processing

pre_processed_speeches = []
list_token_lists = []
unfiltered_sentences = []

exclude = string.punctuation.replace(".", "")
exclude = exclude.replace("!", "")
exclude = exclude.replace("?", "")

# Pre-Processing Helpers
def remove_accents(data):
    return ''.join(x for x in unicodedata.normalize('NFKD', data) if x in string.ascii_letters or x == " ")
  
def remove_misc(data):
  return data.replace('\n', '')

stop_words = set(stopwords.words('english'))
speech_lengths = []




for i, speech in enumerate(speeches):
  
  # Tokenize by sentence, then by lowercase word
  sent_count = 0
  pre_processed_speech_index = []

  for sentence in nltk.sent_tokenize(speech):
    token_list = []
    unfiltered_sentences.append(sentence)
    
    if len(nltk.word_tokenize(sentence)) < MIN_SENTENCE_WORDS:
      continue

    tokens = []
    sent_count += 1

    for word in nltk.word_tokenize(sentence):
      t = word.lower()
      t = remove_accents(t)
      t = remove_misc(t)
      t = str(t).translate(string.punctuation)
      t = t.translate(str.maketrans('', '', exclude))

      token_list.append(t)

    pre_processed_speech_index.append(' '.join(token_list)) # tokenized sentences
  
  if sent_count >= MIN_SPEECH_SENTENCE_COUNT:
    speech_lengths.append(sent_count)
    pre_processed_speeches.append(pre_processed_speech_index)
  
print(f'Number of Speeches Processed: {len(pre_processed_speeches)}')
print(f'Filtered {len(speeches) - len(pre_processed_speeches)} speeches (under 10 sentences in total length)')

df_speeches = pd.DataFrame(list_token_lists)

# Plot histogram of tokenized document lengths
if PLOT_SPEECHLEN_HIST:
  fig = plt.figure(figsize=(8,6))
  plt.suptitle("Histogram of tokenized document (speech) lengths")
  plt.xlabel("Speech Lengths")
  plt.ylabel("Speech Counts")
  n, bins, patches = plt.hist(speech_lengths, bins=50, density=False, facecolor='g', alpha=0.75)
  plt.show()

# Running Cleanlab WITH cleanlab score removal
# Filters unrelated sentences from each individual speech

# Filtered speeches = list of every useful sentence across every speech of the selected president(s)
post_cleanlab_speeches = []
post_cleanlab_sentences = []

all_cleanlab_scores = []

# Embedding and outlier removal
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v1')

filtered_sent_percentages = []

for i, speech in enumerate(pre_processed_speeches):
  try:
    ood = OutOfDistribution()
    original_embeddings = model.encode(speech)
    train_outlier_scores = ood.fit_score(features=original_embeddings)
    # get outlier id's for sentences with outlier scores below cutoff value
    outlier_ids = [i for i, outlier_score in enumerate(train_outlier_scores) if outlier_score < OUTLIER_SCORE_CUTOFF]

    if PRINT_CLEANLAB_ANALYSIS:
      filtered_sentences = [s for i, s in enumerate(speech) if i in outlier_ids]
      filtered_percent = round((len(filtered_sentences) / len(speech)) * 100) 
      filtered_sent_percentages.append(filtered_percent)

      # Metrics
      
      average_cleanlab_score = float(np.mean(train_outlier_scores))
      variance_cleanlab_score = float(sum((x - average_cleanlab_score)**2 for x in train_outlier_scores) / (len(train_outlier_scores) - 1))
      std_cleanlab_score = float(np.sqrt(variance_cleanlab_score))
      min_cleanlab_score = float(min(train_outlier_scores))
      max_cleanlab_score = float(max(train_outlier_scores))

      all_cleanlab_scores.extend(train_outlier_scores)
      
      print(f'Speech: {i}')
      print("Cleanlab Metrics:")
      print(f'  Percent Sentences Filtered: {filtered_percent}% out of {len(speech)} Sentences')
      print(f'  Average: {round(average_cleanlab_score, 3)}')
      print(f'  Variance: {round(variance_cleanlab_score, 3)}')
      print(f'  STDev: {round(std_cleanlab_score, 3)}')
      print(f'  Min: {round(min_cleanlab_score, 3)}')
      print(f'  Max: {round(max_cleanlab_score, 3)}')
      print("Filtered Sentences:")
      for i, s in enumerate(filtered_sentences):
        print(f'  {i}: {s}')
      print("\n\n")

    speech_cleanlab = [s for i, s in enumerate(speech) if i not in outlier_ids]

    post_cleanlab_speeches.append(speech_cleanlab)

    for sentence in speech_cleanlab:
      post_cleanlab_sentences.append(sentence)
  except:
    continue

print(f'Cleanlab score: {all_cleanlab_scores}')

filtered_speech_embeddings = model.encode(post_cleanlab_sentences) # embedding
unfiltered_speech_embeddings = model.encode(unfiltered_sentences) 


# if PRINT_CLEANLAB_ANALYSIS:
#   # print(f'Unfiltered Speech Shape: {model.encode(pre_processed_speeches).shape}') vcc
#   print(f'Filtered Speech Shape: {filtered_speech_embeddings.shape}')
#   print(f'Filtered Speech Shape Z Score: {filtered_speech_embeddings_z_score.shape}')
#   print(f'Average percentage of filtered sentences per speech (cutoff value  of {OUTLIER_SCORE_CUTOFF}): {sum(filtered_sent_percentages) / len(filtered_sent_percentages)}')
#   print(f'Average percentage of filtered z score sentences per speech (cutoff value  of {Z_SCORE_CUTOFF}): {sum(filtered_sent_percentages_z_score) / len(filtered_sent_percentages_z_score)}')

all_z_scores = z_score(all_cleanlab_scores)
      average_cleanlab_score = float(np.mean(all_cleanlab_scores))
      variance_cleanlab_score = float(sum((x - average_cleanlab_score)**2 for x in all_cleanlab_scores) / (len(all_cleanlab_scores) - 1))
      std_cleanlab_score = float(np.sqrt(variance_cleanlab_score))
      min_cleanlab_score = float(min(all_cleanlab_scores))
      max_cleanlab_score = float(max(all_cleanlab_scores))
      average_z_score = float(np.mean(all_z_scores))
      variance_z_score = float(sum((x - average_z_score)**2 for x in all_z_scores) / (len(all_z_scores) - 1))
      std_z_score = float(np.sqrt(variance_z_score))
      min_z_score = float(min(all_z_scores))
      max_z_score = float(max(all_z_scores))
      print("Cleanlab Metrics:")
      print(f'  Average: {round(average_cleanlab_score, 3)}')
      print(f'  Variance: {round(variance_cleanlab_score, 3)}')
      print(f'  STDev: {round(std_cleanlab_score, 3)}')
      print(f'  Min: {round(min_cleanlab_score, 3)}')
      print(f'  Max: {round(max_cleanlab_score, 3)}')
      print("Cleanlab with Z Score Metrics:")
      print(f'  Average: {round(average_z_score, 3)}')
      print(f'  Variance: {round(variance_z_score, 3)}')
      print(f'  STDev: {round(std_z_score, 3)}')
      print(f'  Min: {round(min_z_score, 3)}')
      print(f'  Max: {round(max_z_score, 3)}')

# Cleanlab and Z score Histogram

cleanlab_histogram_cutoff = OUTLIER_SCORE_CUTOFF
num_bins = 50

# Cleanlab Histogram
fig = plt.figure(figsize=(24, 8))
n, bins, patches = plt.hist(all_cleanlab_scores, bins=num_bins, color='blue', alpha=0.8) # alpha is transparency of bars
sorted_data = np.sort(all_cleanlab_scores)
count = len([x for x in sorted_data if x < cleanlab_histogram_cutoff])
# val = np.min(sorted_data[n_smallest_num - 1])
idx = np.searchsorted(bins, cleanlab_histogram_cutoff, side='left')
x = bins[idx]
plt.axvline(x=x, color='red', linestyle='--')
# plt.xlim(6,14)  # Limits x axis range
# plt.ylim(0,10)  # Limits y axis range
plt.xlabel('Cleanlab score')
plt.ylabel('Frequency')
plt.title('Histogram of Cleanlab Score Data')
# plt.xlim(3,15)  # Limits x axis range
# plt.ylim(0,16)  # Limits y axis range
# for i in range(len(patches)):
#     plt.text(patches[i].get_x() + patches[i].get_width()/2.0, patches[i].get_height(),
#              int(n[i]), ha='center', va='bottom')
plt.show()

# Cleanlab with Z Score Histogram
fig = plt.figure(figsize=(24, 8))
n, bins, patches = plt.hist(all_z_scores, bins=num_bins, color='blue', alpha=0.8) # alpha is transparency of bars
sorted_data = np.sort(all_z_scores)
z_score_histogram_cutoff = np.min(sorted_data[count - 1])
z_score_count = len([x for x in sorted_data if x < z_score_histogram_cutoff])
idx = np.searchsorted(bins, z_score_histogram_cutoff, side='left')
x = bins[idx]
plt.axvline(x=x, color='red', linestyle='--')
# plt.xlim(6,14)  # Limits x axis range
# plt.ylim(0,10)  # Limits y axis range
plt.xlabel('Z score of cleanlab score')
plt.ylabel('Frequency')
plt.title('Histogram of Z Score of Cleanlab Data')
# for i in range(len(patches)):
#     plt.text(patches[i].get_x() + patches[i].get_width()/2.0, patches[i].get_height(),
#              int(n[i]), ha='center', va='bottom')
plt.show()
print(f'Cleanlab')
print(f'  Smallest Cleanlab Number Score: {cleanlab_histogram_cutoff}')
print(f'  Percent Filtered Out: {round(float((count/len(all_cleanlab_scores))*100),2)}%')

print(f'Z Score')
print(f'  Smallest Z Score Number Score: {round(float(z_score_histogram_cutoff),3)}')
print(f'  Percent Filtered Out: {round(float((z_score_count/len(all_z_scores))*100),2)}%')

# PCA-95 Dimensionality Reduction
pca = PCA(n_components=0.95)
reduced_embedding = pca.fit_transform([f for f in filtered_speech_embeddings])  # filtered speech embedding is using post_cleanlab_sentences variable
reduced_unfiltered_embedding = pca.fit_transform([f for f in unfiltered_speech_embeddings])
print(reduced_embedding.shape)
print(reduced_unfiltered_embedding.shape)

# Filtered UMAP Clustering
reducer = umap.UMAP(n_components=2)
sentences_embeddings_reduced = reducer.fit_transform(reduced_embedding)

# Apply KMeans clustering to the reduced embeddings
n_clusters = num_filtered_clusters
kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=kmeans_seed)
kmeans.fit(reduced_embedding)

# Get the cluster labels for each sentence and plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(10, 10))
# plt.title("Cognitive Map: Cleanlab Filtered")
plt.scatter(sentences_embeddings_reduced[:, 0], sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=8) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
# plt.xlim(6,14)  # Limits x axis range
# plt.ylim(0,10)  # Limits y axis range

kmeans_labels_sorted_data = [[] for i in range(n_clusters)]
embeddings_by_cluster = [[] for i in range(n_clusters)]
for i, label in enumerate(labels):
  kmeans_labels_sorted_data[label].append(i)
  embeddings_by_cluster.append(reduced_embedding[i])

plt.show()

# Does the two dimensions just represent the visual cluster comparison? KMeans is nonlinear

print(reduced_embedding.shape)
print(kmeans.n_clusters)
# Concentrated UMAP Plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(10, 10))
plt.title("Cognitive Map - Filtered" + "\nClusters: {}".format(n_clusters) + "\nCleanlab Cutoff Score: {}".format(OUTLIER_SCORE_CUTOFF)+ "\nLemmatized Words: {}".format(num_lemmatized_words))
plt.scatter(sentences_embeddings_reduced[:, 0], sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=10) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
plt.xlim(3,15)  # Limits x axis range
plt.ylim(0,16)  # Limits y axis range
plt.show()

# ADD WORD CLOUD CODE
#Filtered
# Word Cloud
#Original method - probably using this

n_clusters = num_filtered_clusters
kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=kmeans_seed)
kmeans.fit(reduced_embedding)
labels = kmeans.labels_
num_sentences_all = []

# Add in when stop words is needed
additional_stopwords = ['thank','may', 'act', 'will', 'good', 'make', 'get', 'need', 'got', 'one', 'day', 'going', 'want', 'many', 'must', 'well', 'thing',
                        'say','new', 'much', 'still', 'first', 'ago', 'bad', 'next', 'yet', 'way', 'saw', 'big', 'know', 'keep', 'use', 'part', 'mean'
                        'tell', 'america', 'american', 'united states', 'us', 'usa', 'long', 'let', 'great', 'said', 'think', 'put', 'nation', 'hard'
                        'man', 'ask', 'people', 'time', 'year', 'back', 'went', 'years', 'came']
stop_words = set(stopwords.words('english'))
stop_words.update(additional_stopwords)

# List of tokenized sentences
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(post_cleanlab_sentences)

# Get the words and their tf-idf scores
feature_names = tfidf_vectorizer.get_feature_names_out()
scores = tfidf_matrix.toarray().mean(axis=0)

# Sort the words by their tf-idf scores
sorted_words = sorted(zip(feature_names, scores), key=lambda x: x[1])

lowest_tfidf_words = []
for word, score in sorted_words[:50]:
    lowest_tfidf_words.append(word)
#     print(f"{word}: {score:.4f}")
print(lowest_tfidf_words)

full_cluster_sentences = []
#labels = kmeans.labels_



for i in range(kmeans.n_clusters):

    # Get the indices of sentences belonging to the current cluster
    cluster_indices = np.where(labels == i)[0]
    cluster_sentences = [post_cleanlab_sentences[index] for index in cluster_indices]
    full_cluster_sentences.append(cluster_sentences)
    num_sentences = len(cluster_sentences)
    num_sentences_all.append(num_sentences)
    # Combine the sentences into a single string
    cluster_text = " ".join(cluster_sentences)
    cluster_text =" ".join([ word for word in cluster_text.split() if word.lower() not in lowest_tfidf_words and len(word)>2 and word.lower() not in stop_words])
    
    if coherenceRan_Filtered:
       # Generate a word cloud from the cluster text
      wordcloud = WordCloud(max_words=120, width=800, height=800, min_font_size=10, collocations=True, background_color="white").generate(cluster_text)

      # Creates a dictionary of words used in each wordcloud
      # text_dictionary = wordcloud.process_text(cluster_text)
      # word_freq={k: v for k, v in sorted(text_dictionary.items(),reverse=True, key=lambda item: item[1])}
      # rel_freq=wordcloud.words_
      # print(list(word_freq.items())[:10])
      # print(list(rel_freq.items())[:10])

      wordcloud.generate(cluster_text)

      # Plot the word cloud
      fig = plt.figure(figsize=(8, 8))
      plt.figure(figsize=(8, 8), facecolor='white')
      # plt.title("Cluster:{}".format(i)) # comment after the coherence scores are ran
      plt.title("Cluster:{}".format(i) + "\nCoherence Score:{}".format(out[i]) + "\n# of Sentences in Cluster:{}".format(num_sentences)) # comment when ran initially
      plt.imshow(wordcloud, interpolation="bilinear")
      plt.axis("off")
      plt.tight_layout(pad=0)
      # plt.show()

      file_name = f'{timestamp}_{OUTLIER_SCORE_CUTOFF}_{num_lemmatized_words}_Filtered_cluster_{i}_wordcloud.png'
      plt.savefig(folder_path + file_name, dpi=300)
      plt.show()

    
initialWordcloudRan_Filtered = True
num_sentences_all_DF = pd.DataFrame(num_sentences_all)
num_sentences_all_DF.to_csv('num_sentences_all_DF.csv')

#Filtered coherence scores output
word2vec_output_file = '/content/word2vec.txt'
model = KeyedVectors.load_word2vec_format(word2vec_output_file, binary=False)
result = model.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)
print(result)

if(initialWordcloudRan_Filtered):
  out = calcCoherence(full_cluster_sentences)
  print(out)
  print(sum(out)/len(out))
  out_DF = pd.DataFrame(out)
  file_name = f'{timestamp}_coherence_scores_Filtered_{OUTLIER_SCORE_CUTOFF}_{num_lemmatized_words}_n{num_filtered_clusters}.csv'
  # out_DF.to_csv(folder_path + file_name)
  coherenceRan_Filtered = True

#Plot descending coherence score values
# Filtered
fig = plt.figure(figsize=(24, 8))
sorted_values = sorted(out, reverse=True)
labels_bar = ['{}'.format(i+1) for i in range(len(out))]
plt.bar(labels_bar, sorted_values)
for i, out in enumerate(sorted_values):
    plt.text(i, out, round(out,3), ha='center', va='bottom')
plt.xlabel('Cluster bars')
plt.ylabel('Coherence score')
plt.title('Coherence Score Ranking; Descending Order')
plt.show()

#  coherence score graph (changes n_clusters)
#Filtered
coherence_score_avgs = []
for x in range(1,50):
  kmeans = KMeans(n_clusters = x, n_init=10, random_state=kmeans_seed)
  kmeans.fit(reduced_embedding)
  # print(reduced_embedding.shape)
  full_cluster_sentences_temp = []
  labels = kmeans.labels_
  for i in range(kmeans.n_clusters): # 10 clusters now
      # Get the indices of sentences belonging to the current cluster
      cluster_indices = np.where(labels == i)[0]
      # print(cluster_indices)
      cluster_sentences = [post_cleanlab_sentences[index] for index in cluster_indices]
      full_cluster_sentences_temp.append(cluster_sentences)
  coherence_Scores = calcCoherence(full_cluster_sentences_temp)
  coherence_Scores_Average = float(np.mean(coherence_Scores))
  coherence_score_avgs.append(coherence_Scores_Average)
  print(x, "Clusters:", coherence_Scores_Average)

coherence_score_avgs.insert(0,0) # add a 0 to the beginning of the list so the index correlates to the number of clusters
print(coherence_score_avgs)

#Save coherence score to CSV
coherence_score_avgs_DF = pd.DataFrame(coherence_score_avgs)
coherence_score_avgs_DF.to_csv('coherence_score_avgs_filtered_.5_10.csv')

# Plot Coherence Score averages for Filtered
plt.figure(figsize=(20, 10))
plt.plot(np.arange(0, len(coherence_score_avgs)) , coherence_score_avgs)
plt.title('Coherence Score vs # of Clusters; Cleanlab Filtered')
plt.axvline(x=40, color='red', linestyle='--')
plt.xlabel('# of clusters')
plt.ylabel('Coherence Score')
plt.xlim(10,49)  # Limits x axis range
# plt.ylim(0,13)  # Limits y axis range
plt.show()

# UMAP Clustering for Unfiltered Speeches
reducer = umap.UMAP(n_components=2)
unfiltered_sentences_embeddings_reduced = reducer.fit_transform(reduced_unfiltered_embedding)
n_clusters = num_unfiltered_clusters

# Apply KMeans clustering to the unfiltered embeddings
kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=kmeans_seed)
kmeans.fit(reduced_unfiltered_embedding)

# Get the cluster labels for each sentence and plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(10, 10))
plt.title("Cognitive Map: Unfiltered Embeddings")
plt.scatter(unfiltered_sentences_embeddings_reduced[:, 0], unfiltered_sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=8) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
# plt.xlim(6,14)  # Limits x axis range
# plt.ylim(0,10)  # Limits y axis range
plt.show()

# print(reduced_embedding.shape)
print(kmeans.n_clusters)
# Concentrated Unfiltered UMAP Plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(10, 10))
plt.title("Cognitive Map - Unfiltered" + "\nClusters: {}".format(n_clusters) + "\nLemmatized Words: {}".format(num_lemmatized_words))
plt.scatter(unfiltered_sentences_embeddings_reduced[:, 0], unfiltered_sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=10) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
plt.xlim(0,18)  # Limits x axis range
plt.ylim(-5,12)  # Limits y axis range
plt.show()

# UNFILTERED WORD CLOUD CODE
# Word Cloud
#Original method - probably using this

# Add in when stop words is needed
additional_stopwords = ['thank','may', 'act', 'will', 'good', 'make', 'get', 'need', 'got', 'one', 'day', 'going', 'want', 'many', 'must', 'well', 'thing',
                        'say','new', 'much', 'still', 'first', 'ago', 'bad', 'next', 'yet', 'way', 'saw', 'big', 'know', 'keep', 'use', 'part', 'mean'
                        'tell', 'america', 'american', 'united states', 'us', 'usa', 'long', 'let', 'great', 'said', 'think', 'put', 'nation', 'hard'
                        'man', 'ask', 'people', 'time', 'year', 'back', 'went', 'years', 'came']
stop_words = set(stopwords.words('english'))
stop_words.update(additional_stopwords)
num_sentences_all = []

# List of tokenized sentences
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(unfiltered_sentences)

# Get the words and their tf-idf scores
feature_names = tfidf_vectorizer.get_feature_names_out()
scores = tfidf_matrix.toarray().mean(axis=0)

# Sort the words by their tf-idf scores
sorted_words = sorted(zip(feature_names, scores), key=lambda x: x[1])

lowest_tfidf_words = []
for word, score in sorted_words[:50]:
    lowest_tfidf_words.append(word)
#     print(f"{word}: {score:.4f}")
print(lowest_tfidf_words)

unfiltered_full_cluster_sentences = []
#labels = kmeans.labels_

for i in range(kmeans.n_clusters): # 38 clusters now 
    # Get the indices of sentences belonging to the current cluster
    cluster_indices = np.where(labels == i)[0]
    # print(kmeans.n_clusters, len(cluster_indices), )
    cluster_sentences = [unfiltered_sentences[index] for index in cluster_indices]
    unfiltered_full_cluster_sentences.append(cluster_sentences)
    num_sentences = len(cluster_sentences)
    num_sentences_all.append(num_sentences)
    # Combine the sentences into a single string
    cluster_text = " ".join(cluster_sentences)
    cluster_text =" ".join([ word for word in cluster_text.split() if word.lower() not in lowest_tfidf_words and len(word)>2 and word.lower() not in stop_words])
    
    if coherenceRan_Unfiltered:
      # Generate a word cloud from the cluster text
      wordcloud = WordCloud(max_words=120, width=800, height=800, min_font_size=10, collocations=True, background_color="white").generate(cluster_text)

      # Creates a dictionary of words used in each wordcloud
      # text_dictionary = wordcloud.process_text(cluster_text)
      # word_freq={k: v for k, v in sorted(text_dictionary.items(),reverse=True, key=lambda item: item[1])}
      # rel_freq=wordcloud.words_
      # print(list(word_freq.items())[:10])
      # print(list(rel_freq.items())[:10])

      wordcloud.generate(cluster_text)

      # Plot the word cloud
      plt.figure(figsize=(8, 8), facecolor='white')
      # plt.title("Cluster:{}".format(i)) # comment after the coherence scores are ran
      plt.title("Cluster:{}".format(i) + "\nCoherence Score:{}".format(out_unfiltered[i])+ "\n# of Sentences in Cluster:{}".format(num_sentences)) # comment when ran initially
      plt.imshow(wordcloud, interpolation="bilinear")
      plt.axis("off")
      plt.tight_layout(pad=0)
      
      file_name = f'{timestamp}_{num_lemmatized_words}_Unfiltered_cluster_{i}_wordcloud.png'
      plt.savefig(folder_path + file_name, dpi=300)
      plt.show()

initialWordcloudRan_Unfiltered = True
num_sentences_all_DF = pd.DataFrame(num_sentences_all)
num_sentences_all_DF.to_csv('num_sentences_all_Unfiltered_DF.csv')

#Unfiltered coherence scores output
word2vec_output_file = '/content/word2vec.txt'
model = KeyedVectors.load_word2vec_format(word2vec_output_file, binary=False)
result = model.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)
print(result)

if(initialWordcloudRan_Unfiltered):
  out_unfiltered = calcCoherence(unfiltered_full_cluster_sentences)
  print(out_unfiltered)
  print(sum(out_unfiltered)/len(out_unfiltered))
  out_unfiltered_DF = pd.DataFrame(out_unfiltered)
  file_name = f'{timestamp}_coherence_scores_Unfiltered_{num_lemmatized_words}_n{num_unfiltered_clusters}.csv'
  # out_DF.to_csv(folder_path + file_name)
  coherenceRan_Unfiltered = True

#Plot descending coherence score values
# Unfiltered
fig = plt.figure(figsize=(24, 8))
sorted_values = sorted(out_unfiltered, reverse=True)
labels_bar = ['Bar {}'.format(i+1) for i in range(len(out_unfiltered))]
plt.bar(labels_bar, sorted_values)
for i, out_unfiltered in enumerate(sorted_values):
    plt.text(i, out_unfiltered, round(out_unfiltered,3), ha='center', va='bottom')
plt.xlabel('Cluster bars')
plt.ylabel('Coherence score')
plt.title('Coherence Score Ranking; Descending Order')
plt.show()

#  coherence score graph (changes n_clusters)
#unFiltered
coherence_score_avgs_unfiltered = []
for x in range(1,50):
  kmeans = KMeans(n_clusters = x, n_init=10, random_state=kmeans_seed)
  kmeans.fit(reduced_unfiltered_embedding)
  full_cluster_sentences_unfiltered_temp = []
  labels = kmeans.labels_
  for i in range(kmeans.n_clusters): # 10 clusters now
      # Get the indices of sentences belonging to the current cluster
      cluster_indices = np.where(labels == i)[0]
      cluster_sentences = [unfiltered_sentences[index] for index in cluster_indices]
      full_cluster_sentences_unfiltered_temp.append(cluster_sentences)
  coherence_Scores = calcCoherence(full_cluster_sentences_unfiltered_temp)
  coherence_Scores_Average = float(np.mean(coherence_Scores))
  coherence_score_avgs_unfiltered.append(coherence_Scores_Average)
  print(x, "Clusters:", coherence_Scores_Average)

coherence_score_avgs_unfiltered.insert(0,0) # add a 0 to the beginning of the list so the index correlates to the number of clusters
print(coherence_score_avgs_unfiltered)

#Save coherence score to CSV
coherence_score_avgs_DF = pd.DataFrame(coherence_score_avgs_unfiltered)
coherence_score_avgs_DF.to_csv('coherence_score_avgs_unfiltered.csv')

# Plot Coherence Score averages for Unfiltered
plt.figure(figsize=(20, 10))
plt.plot(np.arange(0, len(coherence_score_avgs_unfiltered)) , coherence_score_avgs_unfiltered)
plt.title('Coherence Score vs # of Clusters; Cleanlab Unfiltered')
plt.axvline(x=23, color='red', linestyle='--')
plt.xlabel('# of clusters')
plt.ylabel('Coherence Score')
plt.xlim(5,49)  # Limits x axis range
# plt.ylim(0,13)  # Limits y axis range
plt.show()

# --------------------------Code Below Is Trials and NOT Implemented----------------------------------------------------------------------------

# LDA 
# filtered_speech_embeddings = model.encode(post_cleanlab_sentences) # embedding
# unfiltered_speech_embeddings = model.encode(unfiltered_sentences)
additional_stopwords = ['may', 'act', 'will', 'good', 'make', 'get', 'need', 'got', 'one', 'day', 'going', 'want', 'many', 'must', 'well', 'thing',
                        'say','new', 'much', 'still', 'first', 'ago', 'bad', 'next', 'yet', 'way', 'saw', 'big', 'know', 'keep', 'use', 'part', 'mean'
                        'tell', 'america', 'american', 'united states', 'us', 'usa', 'long', 'let', 'great', 'said', 'think', 'put', 'nation', 'hard'
                        'man', 'ask', 'people', 'time', 'year', 'back', 'went', 'years', 'came', 'united  states', '(', ':', ')', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', ',', '/', '\\' + string.ascii_letters]
stop_words = set(stopwords.words('english'))
stop_words.update(additional_stopwords)

documents = speeches
documents = [' '.join([word for word in string.split() if word.lower() not in stop_words]) for string in documents]

# print(documents[0])
tokenized_docs = [doc.lower().split() for doc in documents]

# print(tokenized_docs)
# Create a dictionary from the tokenized documents
dictionary = corpora.Dictionary(tokenized_docs)

# Create a bag-of-words representation of the documents
corpus = [dictionary.doc2bow(doc) for doc in tokenized_docs]


# Train the LDA model
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus, 
                                            id2word=dictionary, 
                                            num_topics=35, 
                                            random_state=42,
                                            passes=10)
#pprint(lda_model.print_topics())

# Generate word clouds for each topic
for topic_id in range(lda_model.num_topics):
    # Get the most significant words for the topic
    topic_words = lda_model.show_topic(topic_id, topn=10)
    # Create a dictionary of the topic words and their weights
    word_weights = {word: weight for word, weight in topic_words}
    # Generate a word cloud for the topic
    wc = WordCloud(background_color="white", 
                   width=800, 
                   height=800, 
                   max_words=120, 
                   min_font_size=10,).generate_from_frequencies(word_weights)
    # Plot the word cloud
    plt.figure(figsize=(8, 8))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Topic #{topic_id}")
    plt.show()

from sklearn.neighbors import NearestNeighbors


####### FUNCTIONS (main code at end) ###################
# # find nearest neighbors given embeddings
def nn(x):
  nbrs = NearestNeighbors(n_neighbors=numNeighbors).fit(x)
  distances, indices = nbrs.kneighbors()
  return distances, indices

# Get neighborhood score of clusters

def categoryScores(labels, catNeighbors): # load labels and list of neighbors

  catScores = []
  
  for descLabelIdx in range(len(set(labels))): # loop through set of cluster numbers
    
    classCount = labels.count(descLabelIdx) #count number of desc that have current label

    q = 0
    for i in range(len(labels)): # loop through labels of each description
      f = 0
      if labels[i]==descLabelIdx:        
        catNeighbor = catNeighbors[i]          
        for n in catNeighbor:
          curNeighborsLabel = labels[n]
          if curNeighborsLabel == descLabelIdx:
            f = f + 1 # increment count of number of neighbors that are of the same cluster
        # use formula to get score
        f = f / len(catNeighbors[i])
        p = classCount / len(labels)
        q = q + (f-p) / (f*(1-p)+(1-f)*p)
    Q = q / classCount
    #catScores.append([descLabelIdx, Q]) # output list will have lists of size 2 with cluster number and score
    catScores.append(Q)

  return catScores


############## MAIN CODE #####################

 # User inputs

labels = kmeans.labels_
# labels is a 1-D list of corresponding to the cluster every sentence belongs to
  # ex. [1, 4, 325, 32, ...]

descEmbeddings = reduced_embedding
# descEmbeddings is a list of all the embeddings corresponding to each sentence. Same as in the other code.
  # ex. [
  #         [234432, 42342, 423424, 423, ..............................],
  #         [234432, 42342, 423424, 423, ..............................],
  #         [234432, 42342, 423424, 423, ..............................],
  #          .
  #          .
  #          .
  #     ]

numNeighbors = 3 + 1 # Number of neighbors. Leave as is for 3 nearest neighbors. (Will be 1 more than n).
neighbor_distances, neighbor_indices = nn(descEmbeddings) # Get neigbhor_indices which is a 2-D list of nearest neighbors for each point.
neighbors = neighbor_indices.tolist() # Get neibhbors from indices

catScores = categoryScores(labels.tolist(), neighbors) # Get final scores
print(catScores)

df = pd.DataFrame(catScores)
df.to_csv('catScoresFiltered6.csv')

#remove common sentences (sentences with alot of bad words)
unique_unfiltered_sentences = list(set(unfiltered_sentences))
print(len(unfiltered_sentences), len(unique_unfiltered_sentences))

#NEW FILTER
#CHECK HERE IF WORKS
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import KeyedVectors


word2vec_output_file = '/content/word2vec.txt'
# load GloVe model
glove_model = KeyedVectors.load_word2vec_format(word2vec_output_file, binary=False)
# define dataset
dataset = unique_unfiltered_sentences
#dataset = ['This is a sample sentence.', 'The quick brown fox jumps over the lazy dog.', 'This is another sample sentence.', 'The quick brown fox jumps over the lazy dog again.']

# define function to calculate GloVe score for a sentence
def calculate_glove_score(sentence):
    # tokenize sentence into words
    words = word_tokenize(sentence)
    # calculate mean GloVe vector for words in sentence
    glove_vector = np.mean([glove_model[word] for word in words if word in glove_model.vocab], axis=0)
    # calculate rank of GloVe vector among all vectors in model
    rank = len([x for x in glove_model.similar_by_vector(glove_vector, topn=len(glove_model.vocab)) if x[0] in words])
    # divide rank by number of words in sentence
    score = rank / len(words)
    return score

# calculate GloVe scores for all sentences in dataset
scores = [calculate_glove_score(sentence) for sentence in dataset]
#cuttoff for removing sentences? look at distribution, invert to z scores and standardize it, then look at stdev and find point where it makes sense
# print scores
#print(scores)
z_scores = (scores - np.mean(scores)) / np.std(scores)
std_dev = np.std(z_scores)
cutoff = np.mean(scores) - 2 * std_dev
glove_filtered_sentences = [sentence for i, sentence in enumerate(dataset) if scores[i] > cutoff]
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v1')
glove_filtered_sentence_embeddings = model.encode(glove_filtered_sentences)

# PCA-95 Dimensionality Reduction
pca = PCA(n_components=0.95)
glove_reduced_embedding = pca.fit_transform([f for f in glove_filtered_sentence_embeddings])  # glove filtered sentence embedding is using post_cleanlab_sentences variable
print(glove_reduced_embedding.shape)

# Filtered UMAP Clustering
reducer = umap.UMAP(n_components=2)
sentences_embeddings_reduced = reducer.fit_transform(glove_reduced_embedding)

# Apply KMeans clustering to the reduced embeddings
n_clusters = 38


kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=kmeans_seed)
kmeans.fit(glove_reduced_embedding)

# Get the cluster labels for each sentence and plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(12, 6))
plt.title("Cognitive Map: Cleanlab Filtered")
plt.scatter(sentences_embeddings_reduced[:, 0], sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=8) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
# plt.xlim(6,14)  # Limits x axis range
# plt.ylim(0,10)  # Limits y axis range

kmeans_labels_sorted_data = [[] for i in range(n_clusters)]
embeddings_by_cluster = [[] for i in range(n_clusters)]
for i, label in enumerate(labels):
  kmeans_labels_sorted_data[label].append(i)
  embeddings_by_cluster.append(glove_reduced_embedding[i])

plt.show()

# Does the two dimensions just represent the visual cluster comparison? KMeans is nonlinear

print(glove_reduced_embedding.shape)
print(kmeans.n_clusters)
# Concentrated UMAP Plot
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
plt.figure(figsize=(20, 5))
plt.title("Cluster Map: Cleanlab Filtered Reduced Embeddings")
plt.scatter(sentences_embeddings_reduced[:, 0], sentences_embeddings_reduced[:, 1], c=labels, cmap='jet', s=10) # s = dot size, cmap variables include cmap = 'jet', 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
plt.xlim(3,15)  # Limits x axis range
plt.ylim(0,16)  # Limits y axis range
plt.show()

# ADD WORD CLOUD CODE
#Filtered
# Word Cloud
#Original method - probably using this

# Add in when stop words is needed
additional_stopwords = ['may', 'act', 'will', 'good', 'make', 'want', 'get', 'need', 'got', 'one', 'will', 'day', 'going', 'want', 'many']
stop_words = set(stopwords.words('english'))
stop_words.update(additional_stopwords)

# List of tokenized sentences
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(glove_filtered_sentences)

# Get the words and their tf-idf scores
feature_names = tfidf_vectorizer.get_feature_names_out()
scores = tfidf_matrix.toarray().mean(axis=0)

# Sort the words by their tf-idf scores
sorted_words = sorted(zip(feature_names, scores), key=lambda x: x[1])

lowest_tfidf_words = []
for word, score in sorted_words[:50]:
    lowest_tfidf_words.append(word)
#     print(f"{word}: {score:.4f}")
print(lowest_tfidf_words)

full_cluster_sentences = []
#labels = kmeans.labels_
nclusters = 38
for i in range(kmeans.n_clusters): # 38 clusters now 
    # Get the indices of sentences belonging to the current cluster
    cluster_indices = np.where(labels == i)[0]
    cluster_sentences = [glove_filtered_sentences[index] for index in cluster_indices]
    full_cluster_sentences.append(cluster_sentences)

    # Combine the sentences into a single string
    cluster_text = " ".join(cluster_sentences)
    cluster_text =" ".join([ word for word in cluster_text.split() if word.lower() not in lowest_tfidf_words and len(word)>2 and word.lower() not in stop_words])
    # Generate a word cloud from the cluster text


    # wordcloud = WordCloud(min_font_size=4, 
    #                       mask=mask,
    #                       width=mask.shape[1],
    #                       height=mask.shape[0],
    #                       stopwords=lowest_tfidf_words, 
    #                       background_color="white",
    #                       contour_width=1,
    #                       contour_color="black")
    wordcloud = WordCloud(max_words=120, width=800, height=800, min_font_size=10).generate(cluster_text)
    wordcloud.generate(cluster_text)

    # Plot the word cloud
    plt.figure(figsize=(8, 8), facecolor=None)
    plt.title("Cluster:{}".format(i)) # comment after the coherence scores are ran
    # plt.title("Cluster:{}".format(i) + "\nCoherence Score:{}".format(out[i])) # comment when ran initially
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.axis("off")
    plt.tight_layout(pad=0)

    plt.show()

# Rishabhs
#Filtered
from sklearn.feature_extraction.text import TfidfVectorizer
from wordcloud import STOPWORDS
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import WordNetLemmatizer
import pandas as pd
from statistics import mean
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.models import KeyedVectors

# pre_processed_speech_sentences

clusterStrings = full_cluster_sentences


# if 'result' in globals():
#   print('yes')
# else:

  # Download GloVe embeddings
  
  #glove_input_file = '/content/glove.6B.300d.txt'
word2vec_output_file = '/content/word2vec.txt'
# The first step is to convert the GloVe file format to the word2vec file format. 
# The only difference is the addition of a small header line. This can be done by calling the 
# glove2word2vec() function.

#glove2word2vec(glove_input_file, word2vec_output_file)
model = KeyedVectors.load_word2vec_format(word2vec_output_file, binary=False)
# calculate: (king - man) + woman = ?
result = model.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)
print(result)


# Get the final coherence scores for each cluster

def calcFinalScores(coherenceScores, finalWeights):
  listScores = []
  for i in range(len(coherenceScores)):
    sum = 0
    for j in range(len(coherenceScores[i])):
      sum += finalWeights[i][j]*coherenceScores[i][j] #here change the 45 to 190
    listScores.append((sum*1000) / 45) # Multiply sum by 1000 to make scores more readable (this can be changed). Divide by 45 to get average. 
  return listScores


# Use temporary weights to get final weights. The weights will be finalized by normalizing them.

def calcFinalWeights(pairWeights):
  finalWeights = []
  for i in range(len(pairWeights)):
    curWeights = pairWeights[i]
    sumWeights = 0
    for j in range(len(curWeights)):
      # sumWeights = sumWeights + math.exp(curWeights[j])
      sumWeights = sumWeights + curWeights[j]
    tempFinalWeights = []
    for j in range(len(curWeights)):
      # tempFinalWeights.append(math.exp(curWeights[j]) / sumWeights)
      tempFinalWeights.append(curWeights[j] / sumWeights) # Normalize the weights
    finalWeights.append(tempFinalWeights)
  # sum = 0
  # for i in range(len(finalWeights[0])):
  #   sum = sum + finalWeights[1][i]
 
  return finalWeights

# This calculates the coherence score of each cluster
# The coherence is calculated by finding the pair-wise similarity between the top 10 words in the cluster.
# The top 10 words are determined using TF-IDF
# Final output will include intermediate scores and weights for the scores.
# Weigting is based on Zipf rank
#------

def calcCoherence1(clusterStrings):
  corpus = clusterStrings # set corpus as the list of clusters with corresponding texts as strings
  corpus = [' '.join(cluster) for cluster in clusterStrings]
  # Use TF-IDF
  vectorizer = TfidfVectorizer(stop_words=list(STOPWORDS), norm=None, smooth_idf=False) 
  X = vectorizer.fit_transform(corpus)
  idf = vectorizer.idf_
  idf = idf - 1
  countVectorizer = CountVectorizer(stop_words=list(STOPWORDS))
  tf = countVectorizer.fit_transform(corpus)
  tf = tf.toarray()
  tfidf = tf*idf

  lemmatizer = WordNetLemmatizer()
  coherenceScores = []
  pairWeights = []

  for i in range(len(clusterStrings)): # loop through all clusters

    df = pd.DataFrame(tfidf[i], index=vectorizer.get_feature_names_out(), columns=["TF-IDF"])
    dfs = df.sort_values('TF-IDF', ascending=False) 

    curList = dfs.index.to_list()
    curListLem = []
    curList10 = []

    # Get top 10 words (lemmatized)
    w = 0
    c = 0
    while c < 10: #change 20 to 10?
      word = curList[w]
      curWord = lemmatizer.lemmatize(word)
      if curWord not in curListLem and curWord in model.vocab:
        curListLem.append(curWord)
        c = c + 1
      w = w + 1

    # Get pair-wise scores
    tempScore = []
    tempPairWeights = []
    for a in range(len(curListLem)):
      for b in range(a, len(curListLem)):
        if a != b:
          w1 = curListLem[a]
          w2 = curListLem[b]
          weight1 = list(model.vocab.keys()).index(w1) # Get Zipf rank of word 1
          weight2 = list(model.vocab.keys()).index(w2) # Get Zipf rank of word 2
          tempPairWeights.append(mean([weight1, weight2]))
          # tempPairWeigts.append(math.log(weight1, 10) + math.log(weight2, 10) / 2)
          tempScore.append(model.similarity(w1, w2))
    pairWeights.append(tempPairWeights)
    coherenceScores.append(tempScore)
  return [pairWeights, coherenceScores] # return list of weights and temporary scores
# wrapper function to calculate coherence scores

def calcCoherence(clusterStrings):
  pairWeights_and_coherenceScores1 = calcCoherence1(clusterStrings)
  pairWeights = pairWeights_and_coherenceScores1[0]
  coherenceScores1 = pairWeights_and_coherenceScores1[1]
  finalWeights = calcFinalWeights(pairWeights)
  finalScores = calcFinalScores(coherenceScores1, finalWeights)
  return finalScores

#Filtered coherence scores output
out = calcCoherence(full_cluster_sentences)
print(out)
print(sum(out)/len(out))

# Segmentation
segmentation  = get_optimal_splits(filtered_speech_embeddings, p) # Splits.
segmented_txt = get_segmented_sentences(post_cleanlab_sentences, segmentation)
segment_list = []
for segment in segmented_txt:
    segment_list.append('Segment ' + str(segmented_txt.index(segment)) + ': ' + str(segment))

seglistDF = pd.DataFrame(segment_list)
seglistDF.to_csv('fullSegmentationList.csv')

# Best Kmeans Seed
#Filtered
n_clusters = 40
out_avgs = []
d = 0
for d in range(50):
  # random_seed = 25
  kmeans = KMeans(n_clusters=n_clusters, n_init=10, random_state=d)
  kmeans.fit(reduced_embedding)
  labels = kmeans.labels_
  full_cluster_sentences = []
  #labels = kmeans.labels_

  for i in range(kmeans.n_clusters):
      # Get the indices of sentences belonging to the current cluster
      cluster_indices = np.where(labels == i)[0]
      cluster_sentences = [post_cleanlab_sentences[index] for index in cluster_indices]
      full_cluster_sentences.append(cluster_sentences)
  
  print(d)
  out = calcCoherence(full_cluster_sentences)
  print(out)
  out_avg = float(np.mean(out))
  print(out_avg)
  print("\n")
  out_avgs.append(out_avg)

out_avgs_DF = pd.DataFrame(out_avgs)
out_avgs_DF.to_csv('out_avgs_n30.csv')
print(out_avgs_DF)